[package]
name = "jessica-knn-points"
version = "0.1.0"
edition = "2021"
authors = ["Alec Dusheck", "Triform"]

[dependencies]
tch.workspace = true
torch-sys.workspace = true

jessica-utils = { path = "../jessica-utils" }

[build-dependencies]
cc.workspace = true

[lints]
workspace = true