[package]
name = "jessica-model-renderer"
version = "0.1.0"
edition = "2021"

[dependencies]
tch.workspace = true
torch-sys.workspace = true
log.workspace = true

jessica-utils = { path = "../jessica-utils" }

[build-dependencies]
cc.workspace = true

[lints]
workspace = true
